### ISSUE TITLE
Meetup — 2013 Oct

### ISSUE THREAD

**Issue by and1truong** [DrupalVietNam/drupalvietnam.org#4]
Please submit your topics & Slide ^^
- Bao: SF2 Best Practises
- Si: CMI
- Sang: Twig
- Andy: DI

**Comment by and1truong** [comment]
Hello @mrsinguyen @sanglt @nqbao ^^

**Comment by mrsinguyen** [comment]
Configuration Management System in Drupal 8.

**Comment by nqbao** [comment]
Let me think about the topic

**Comment by nqbao** [comment]
maybe "Symfony 2 best practices"

**Comment by sanglt** [comment]
Sang sẽ nói về Cache API

**Comment by sanglt** [comment]
Nếu thấy trừu tượng quá thì nói về Twig template

**Comment by mrsinguyen** [comment]
Twig chứ ta. :D
