### ISSUE TITLE
Build a new theme for DrupalVietnam.org

### ISSUE THREAD

**Issue by mrsinguyen** [DrupalVietNam/drupalvietnam.org#5]
Build a new theme for DrupalVietnam.org, use structure like a http://drupal.stackexchange.com.

Deadline: 6 weeks from now
Expense 8 hours per week to work it.

Anyone has an any suggestion please comment bellow this issue.

Thanks

**Comment by and1truong** [comment]
You have budget for it if we have it ontime ^^ — https://www.facebook.com/groups/drupalvn/doc/404584159628313/

**Comment by mrsinguyen** [comment]
Running on http://www.drupalvietnam.org. 
We need fix some error, issue tracker https://drupal.org/project/issues/stack?categories=All
